language: ruby
rvm:
  - 2.4.1

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  
sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false


deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  name: Deployment Bot
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
